### ISSUE TITLE
ISS endpoint

### ISSUE THREAD

**Issue by DJSethDuncan** [lake-afton-public-observatory/lapo-api#3]
Would love to have info on the ISS, where it is now, speed, altitude.

**Comment by nessalc** [comment]
So, which is more useful? Where it is _now_, or when the next overhead visible pass is?

I've created two endpoints for this based on info I can find, one for when the next pass is, and one for current data. Can't seem to find data for speed, though.

I suppose using some fancy trigonometry I could estimate it. For accuracy I'd want to use PyEphem, yet for speed I'd rather use JavaScript. Depends really on the purpose of the endpoint. N2YO has a [widget](https://www.n2yo.com/widgets/) which is fun, and I use [this](https://isstracker.spaceflight.esa.int/) on KAOWichita's [ISS page](https://kaowichita.com/pages/iss/).

Anyway, let me know your thoughts...
